[package]
name = "bolt-ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
# ECS frameworks - we'll use multiple options for testing
bevy = "0.12"
hecs = "0.10"
specs = "0.20"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Performance monitoring
flame = "0.2"

# Testing
criterion = "0.5"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
log = "0.4"
env_logger = "0.10"

# Random number generation
rand = "0.8"

# FFI for Node.js integration
napi = "2.0"
napi-derive = "2.0"

[dev-dependencies]
tokio-test = "0.4"

[[bench]]
name = "ecs_benchmark"
harness = false
