[features]
seeds = false
skip-lint = false

[programs.devnet]
nen_betting = "dyvzd2UHYEvZQDJFx2ryGNQDLJx1rMGmDF3XGjvqQfM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.31.1"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
