[features]
seeds = false
skip-lint = false

[programs.devnet]
nen_betting = "34RNydfkFZmhvUupbW1qHBG5LmASc6zeS3tuUsw6PwC5"
nen_core = "Xs4PKxWNyY1C7i5bdqMh5tNhwPbDbxMXf4YcJAreJcF"
nen_magicblock = "AhGXiWjzKjd8T7J3FccYk51y4D97jGkZ7d7NJfmb3aFX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.31.1"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
