[features]
seeds = false
skip-lint = false

[programs.localnet]
nen_core = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
nen_betting = "C8uJ3ABMU87GjcB8moR1jiiAgYnFUDR17DBfiQE4eUcz"

[programs.devnet]
nen_core = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
nen_betting = "C8uJ3ABMU87GjcB8moR1jiiAgYnFUDR17DBfiQE4eUcz"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.31.1"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
