global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Backend Service Metrics
  - job_name: 'nen-backend'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s

  # AI Service Metrics
  - job_name: 'nen-ai-service'
    static_configs:
      - targets: ['ai-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-master:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: '/nginx-health'
    scrape_interval: 30s

  # Node Exporter (if added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
