personalities:
  standard:
    - id: strategic
      name: Strategic AI
      description: Long-term planning focused AI with calculated moves
      traits:
        aggressiveness: 3
        planning_depth: 8
        risk_tolerance: 4
        adaptation_rate: 6
      parameters:
        search_depth: ${AI_SEARCH_DEPTH_STRATEGIC:-8}
        time_per_move: ${AI_TIME_PER_MOVE_STRATEGIC:-5000}
        evaluation_weight: ${AI_EVAL_WEIGHT_STRATEGIC:-1.2}
    
    - id: aggressive
      name: Aggressive AI
      description: High-risk, high-reward AI with rapid advancement focus
      traits:
        aggressiveness: 9
        planning_depth: 5
        risk_tolerance: 8
        adaptation_rate: 7
      parameters:
        search_depth: ${AI_SEARCH_DEPTH_AGGRESSIVE:-5}
        time_per_move: ${AI_TIME_PER_MOVE_AGGRESSIVE:-3000}
        evaluation_weight: ${AI_EVAL_WEIGHT_AGGRESSIVE:-0.8}
    
    - id: defensive
      name: Defensive AI
      description: Cautious AI focusing on board control and piece safety
      traits:
        aggressiveness: 2
        planning_depth: 7
        risk_tolerance: 2
        adaptation_rate: 4
      parameters:
        search_depth: ${AI_SEARCH_DEPTH_DEFENSIVE:-7}
        time_per_move: ${AI_TIME_PER_MOVE_DEFENSIVE:-6000}
        evaluation_weight: ${AI_EVAL_WEIGHT_DEFENSIVE:-1.5}
    
    - id: adaptive
      name: Adaptive AI
      description: Dynamic AI that adjusts strategy based on opponent behavior
      traits:
        aggressiveness: 5
        planning_depth: 6
        risk_tolerance: 5
        adaptation_rate: 9
      parameters:
        search_depth: ${AI_SEARCH_DEPTH_ADAPTIVE:-6}
        time_per_move: ${AI_TIME_PER_MOVE_ADAPTIVE:-4000}
        evaluation_weight: ${AI_EVAL_WEIGHT_ADAPTIVE:-1.0}

  experimental:
    - id: creative
      name: Creative AI
      description: Unconventional moves and creative strategies
      traits:
        aggressiveness: 6
        planning_depth: 4
        risk_tolerance: 7
        adaptation_rate: 8
      parameters:
        search_depth: ${AI_SEARCH_DEPTH_CREATIVE:-4}
        time_per_move: ${AI_TIME_PER_MOVE_CREATIVE:-3500}
        evaluation_weight: ${AI_EVAL_WEIGHT_CREATIVE:-0.9}
        creativity_bonus: ${AI_CREATIVITY_BONUS:-0.3}
    
    - id: endgame_specialist
      name: Endgame Specialist AI
      description: Expert in endgame scenarios and piece promotion strategies
      traits:
        aggressiveness: 4
        planning_depth: 9
        risk_tolerance: 3
        adaptation_rate: 5
      parameters:
        search_depth: ${AI_SEARCH_DEPTH_ENDGAME:-9}
        time_per_move: ${AI_TIME_PER_MOVE_ENDGAME:-7000}
        evaluation_weight: ${AI_EVAL_WEIGHT_ENDGAME:-1.3}
        endgame_bonus: ${AI_ENDGAME_BONUS:-0.5}

generation_parameters:
  default_count: ${TEST_DATA_DEFAULT_COUNT:-1000}
  batch_size: ${TEST_DATA_BATCH_SIZE:-100}
  max_concurrent: ${TEST_DATA_MAX_CONCURRENT:-4}
  timeout_seconds: ${TEST_DATA_TIMEOUT:-300}

constraints:
  max_game_length: ${GAME_MAX_LENGTH:-200}
  min_game_length: ${GAME_MIN_LENGTH:-10}
  time_limit_per_game: ${GAME_TIME_LIMIT:-1800}
  memory_limit_mb: ${AI_MEMORY_LIMIT:-512}
  cpu_limit_percent: ${AI_CPU_LIMIT:-80}
