# Nen Platform Frontend - Production Kubernetes Deployment
# Phase 4.2: Production Deployment (Days 111-116)
# Following GI Guidelines: Production-ready, scalable, secure

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nen-frontend
  namespace: nen-platform
  labels:
    app: nen-frontend
    tier: frontend
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nen-frontend
  template:
    metadata:
      labels:
        app: nen-frontend
        tier: frontend
        version: v1.0.0
    spec:
      containers:
      - name: frontend
        image: nen-platform/frontend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: nen-config
              key: api-url
        - name: NEXT_PUBLIC_SOLANA_NETWORK
          valueFrom:
            configMapKeyRef:
              name: nen-config
              key: solana-network
        - name: NEXT_PUBLIC_MAGICBLOCK_SESSION_PROGRAM
          valueFrom:
            configMapKeyRef:
              name: nen-config
              key: magicblock-session-program
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: nen-frontend-service
  namespace: nen-platform
  labels:
    app: nen-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: nen-frontend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nen-frontend-hpa
  namespace: nen-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nen-frontend
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
